In [1]:
!pip install pandas_profiling

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas_profiling as pp
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split # split dataset
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.feature_selection import RFE # for Recursive Feature Elimination 
import xgboost as xgb


In [0]:
data = pd.read_csv("census.csv")

In [22]:
data

age          workclass  ...  native-country  income
0       39          State-gov  ...   United-States   <=50K
1       50   Self-emp-not-inc  ...   United-States   <=50K
2       38            Private  ...   United-States   <=50K
3       53            Private  ...   United-States   <=50K
4       28            Private  ...            Cuba   <=50K
...    ...                ...  ...             ...     ...
45217   33            Private  ...   United-States   <=50K
45218   39            Private  ...   United-States   <=50K
45219   38            Private  ...   United-States   <=50K
45220   44            Private  ...   United-States   <=50K
45221   35       Self-emp-inc  ...   United-States    >50K

[45222 rows x 14 columns]

In [23]:
report = pp.ProfileReport(data)

/usr/local/lib/python3.6/dist-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)


In [24]:
report

In [25]:
data.columns

Index(['age', 'workclass', 'education_level', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [26]:
data['income'].head()

0    <=50K
1    <=50K
2    <=50K
3    <=50K
4    <=50K
Name: income, dtype: object

In [0]:
features_cont=['age','education-num','capital-gain','capital-loss','hours-per-week','income']
features_dummy = ['workclass', 'education_level','marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

In [0]:
X_temp = data[features_dummy]
X_temp2 = data[features_cont]
X_temp3= pd.get_dummies(X_temp)
X_temp4 = pd.concat([X_temp2,X_temp3],axis=1)

In [29]:
Data1 = X_temp4
Data1 

age  education-num  ...  native-country_ Vietnam  native-country_ Yugoslavia
0       39           13.0  ...                        0                           0
1       50           13.0  ...                        0                           0
2       38            9.0  ...                        0                           0
3       53            7.0  ...                        0                           0
4       28           13.0  ...                        0                           0
...    ...            ...  ...                      ...                         ...
45217   33           13.0  ...                        0                           0
45218   39           13.0  ...                        0                           0
45219   38           13.0  ...                        0                           0
45220   44           13.0  ...                        0                           0
45221   35           13.0  ...                        0                           0

[45222 rows x 104 columns]

In [0]:
y = Data1['income']

In [0]:
features = list(Data1.columns)
features.remove('income')

In [0]:
X = Data1[features]

In [33]:
Data1

age  education-num  ...  native-country_ Vietnam  native-country_ Yugoslavia
0       39           13.0  ...                        0                           0
1       50           13.0  ...                        0                           0
2       38            9.0  ...                        0                           0
3       53            7.0  ...                        0                           0
4       28           13.0  ...                        0                           0
...    ...            ...  ...                      ...                         ...
45217   33           13.0  ...                        0                           0
45218   39           13.0  ...                        0                           0
45219   38           13.0  ...                        0                           0
45220   44           13.0  ...                        0                           0
45221   35           13.0  ...                        0                           0

[45222 rows x 104 columns]

In [34]:
report1 = pp.ProfileReport(Data1)
report1

/usr/local/lib/python3.6/dist-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 60)

In [36]:
model=xgb.XGBClassifier()

rfe = RFE(estimator=model,step=1)
rfe.fit(X_train, y_train)
rfe = rfe.fit(X_train, y_train)
rfe.transform(X_train)
rfe.transform(X_test)


array([[57., 14.,  0., ...,  0.,  0.,  0.],
       [27.,  9.,  0., ...,  0.,  0.,  0.],
       [20.,  9.,  0., ...,  0.,  0.,  1.],
       ...,
       [41., 13.,  0., ...,  0.,  0.,  0.],
       [46., 13.,  0., ...,  0.,  0.,  0.],
       [31.,  9.,  0., ...,  0.,  0.,  0.]])

In [0]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 60)

In [37]:
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
#coefficient = model.coef_

In [0]:
#intercept = model.intercept_

In [0]:
#coefficient

array([[-1.39864259, -1.05523211, -0.98790856, -1.50855516, -1.50105961,
         2.06775313,  1.27480748,  2.17368507,  1.68474393,  2.25257644,
         0.85445023, -1.00167309, -1.0762556 , -1.38666905, -1.37218952,
        -1.20757867, -1.56394984, -1.9294437 , -0.95926822, -1.40314613,
        -1.33324753, -0.77496437, -1.14678966, -1.42495425, -0.65042736]])

In [0]:
#intercept

array([-2.48183901])

In [39]:
model.score(X_test, y_test) # accuracy

0.8626077983341932

In [0]:
y_predicted = model.predict(X_test)

In [0]:
#coefficients_pd = pd.DataFrame((list(zip(features, model.coef_ * 1000))), columns = ['Features', 'Coefficients'])

In [0]:
#coefficients_pd

In [0]:
#coefficients_pd.sort_values('Coefficients').set_index('Features').plot(kind = 'barh', color = 'g')

In [41]:
# confusion matrix
cf = confusion_matrix(y_test, y_predicted)
cf

array([[9620,  526],
       [1338, 2083]])

In [42]:
# heatmap of confusion matrix 
sns.heatmap(cf, annot = True)

In [43]:
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

       <=50K       0.88      0.95      0.91     10146
        >50K       0.80      0.61      0.69      3421

    accuracy                           0.86     13567
   macro avg       0.84      0.78      0.80     13567
weighted avg       0.86      0.86      0.86     13567

